apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloudops
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: cloudops-ai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/wyhffw/cloudops-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ADDR
              value: ":8080"
            - name: APP_ENV
              value: "prod"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
