apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cloudops
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: cloudops-ai-platform
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
