apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wyhffw/cloudops-ai-platform.git
    targetRevision: main
    path: k8s/apps/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
